config/routes.rb
Rails.application.routes.draw do
  resources :hotels

  root 'home#index'

end

app/models/hotel.rb
class Hotel < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
     render plain: "Capistrano 自动化部署"
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:id, :ota_channel_id, :third_party_hotel_id, :hotel_brand_id, :name, :address, :open_at, :close_at, :phone, :fax, :zip_code, :is_economic, :is_apartmen, :reocar_city_id, :city_name, :city_id, :business_zone, :business_zone_id, :attached_business_zone, :district, :district_id, :baidu_location, :google_location, :star, :credit_cards, :status, :review_count, :review_good, :review_poor, :review_score, :intro, :description, :traffic, :has_coupon, :themes, :room_total, :facilities, :stay_leave_info, :recommend_level)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: hotel, local: true) do |form| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.text_field :id %>
  </div>

  <div class="field">
    <%= form.label :ota_channel_id %>
    <%= form.text_field :ota_channel_id %>
  </div>

  <div class="field">
    <%= form.label :third_party_hotel_id %>
    <%= form.text_field :third_party_hotel_id %>
  </div>

  <div class="field">
    <%= form.label :hotel_brand_id %>
    <%= form.text_field :hotel_brand_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :open_at %>
    <%= form.datetime_select :open_at %>
  </div>

  <div class="field">
    <%= form.label :close_at %>
    <%= form.datetime_select :close_at %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :fax %>
    <%= form.text_field :fax %>
  </div>

  <div class="field">
    <%= form.label :zip_code %>
    <%= form.text_field :zip_code %>
  </div>

  <div class="field">
    <%= form.label :is_economic %>
    <%= form.check_box :is_economic %>
  </div>

  <div class="field">
    <%= form.label :is_apartmen %>
    <%= form.check_box :is_apartmen %>
  </div>

  <div class="field">
    <%= form.label :reocar_city_id %>
    <%= form.number_field :reocar_city_id %>
  </div>

  <div class="field">
    <%= form.label :city_name %>
    <%= form.text_field :city_name %>
  </div>

  <div class="field">
    <%= form.label :city_id %>
    <%= form.text_field :city_id %>
  </div>

  <div class="field">
    <%= form.label :business_zone %>
    <%= form.text_field :business_zone %>
  </div>

  <div class="field">
    <%= form.label :business_zone_id %>
    <%= form.text_field :business_zone_id %>
  </div>

  <div class="field">
    <%= form.label :attached_business_zone %>
    <%= form.text_field :attached_business_zone %>
  </div>

  <div class="field">
    <%= form.label :district %>
    <%= form.text_field :district %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.text_field :district_id %>
  </div>

  <div class="field">
    <%= form.label :baidu_location %>
    <%= form.text_field :baidu_location %>
  </div>

  <div class="field">
    <%= form.label :google_location %>
    <%= form.text_field :google_location %>
  </div>

  <div class="field">
    <%= form.label :star %>
    <%= form.number_field :star %>
  </div>

  <div class="field">
    <%= form.label :credit_cards %>
    <%= form.text_field :credit_cards %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :review_count %>
    <%= form.number_field :review_count %>
  </div>

  <div class="field">
    <%= form.label :review_good %>
    <%= form.number_field :review_good %>
  </div>

  <div class="field">
    <%= form.label :review_poor %>
    <%= form.number_field :review_poor %>
  </div>

  <div class="field">
    <%= form.label :review_score %>
    <%= form.text_field :review_score %>
  </div>

  <div class="field">
    <%= form.label :intro %>
    <%= form.text_area :intro %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :traffic %>
    <%= form.text_field :traffic %>
  </div>

  <div class="field">
    <%= form.label :has_coupon %>
    <%= form.check_box :has_coupon %>
  </div>

  <div class="field">
    <%= form.label :themes %>
    <%= form.text_field :themes %>
  </div>

  <div class="field">
    <%= form.label :room_total %>
    <%= form.number_field :room_total %>
  </div>

  <div class="field">
    <%= form.label :facilities %>
    <%= form.text_area :facilities %>
  </div>

  <div class="field">
    <%= form.label :stay_leave_info %>
    <%= form.text_field :stay_leave_info %>
  </div>

  <div class="field">
    <%= form.label :recommend_level %>
    <%= form.number_field :recommend_level %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Ota channel</th>
      <th>Third party hotel</th>
      <th>Hotel brand</th>
      <th>Name</th>
      <th>Address</th>
      <th>Open at</th>
      <th>Close at</th>
      <th>Phone</th>
      <th>Fax</th>
      <th>Zip code</th>
      <th>Is economic</th>
      <th>Is apartmen</th>
      <th>Reocar city</th>
      <th>City name</th>
      <th>City</th>
      <th>Business zone</th>
      <th>Business zone</th>
      <th>Attached business zone</th>
      <th>District</th>
      <th>District</th>
      <th>Baidu location</th>
      <th>Google location</th>
      <th>Star</th>
      <th>Credit cards</th>
      <th>Status</th>
      <th>Review count</th>
      <th>Review good</th>
      <th>Review poor</th>
      <th>Review score</th>
      <th>Intro</th>
      <th>Description</th>
      <th>Traffic</th>
      <th>Has coupon</th>
      <th>Themes</th>
      <th>Room total</th>
      <th>Facilities</th>
      <th>Stay leave info</th>
      <th>Recommend level</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.id %></td>
        <td><%= hotel.ota_channel %></td>
        <td><%= hotel.third_party_hotel_id %></td>
        <td><%= hotel.hotel_brand_id %></td>
        <td><%= hotel.name %></td>
        <td><%= hotel.address %></td>
        <td><%= hotel.open_at %></td>
        <td><%= hotel.close_at %></td>
        <td><%= hotel.phone %></td>
        <td><%= hotel.fax %></td>
        <td><%= hotel.zip_code %></td>
        <td><%= hotel.is_economic %></td>
        <td><%= hotel.is_apartmen %></td>
        <td><%= hotel.reocar_city_id %></td>
        <td><%= hotel.city_name %></td>
        <td><%= hotel.city_id %></td>
        <td><%= hotel.business_zone %></td>
        <td><%= hotel.business_zone_id %></td>
        <td><%= hotel.attached_business_zone %></td>
        <td><%= hotel.district %></td>
        <td><%= hotel.district_id %></td>
        <td><%= hotel.baidu_location %></td>
        <td><%= hotel.google_location %></td>
        <td><%= hotel.star %></td>
        <td><%= hotel.credit_cards %></td>
        <td><%= hotel.status %></td>
        <td><%= hotel.review_count %></td>
        <td><%= hotel.review_good %></td>
        <td><%= hotel.review_poor %></td>
        <td><%= hotel.review_score %></td>
        <td><%= hotel.intro %></td>
        <td><%= hotel.description %></td>
        <td><%= hotel.traffic %></td>
        <td><%= hotel.has_coupon %></td>
        <td><%= hotel.themes %></td>
        <td><%= hotel.room_total %></td>
        <td><%= hotel.facilities %></td>
        <td><%= hotel.stay_leave_info %></td>
        <td><%= hotel.recommend_level %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @hotel.id %>
</p>

<p>
  <strong>Ota channel:</strong>
  <%= @hotel.ota_channel %>
</p>

<p>
  <strong>Third party hotel:</strong>
  <%= @hotel.third_party_hotel_id %>
</p>

<p>
  <strong>Hotel brand:</strong>
  <%= @hotel.hotel_brand_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @hotel.address %>
</p>

<p>
  <strong>Open at:</strong>
  <%= @hotel.open_at %>
</p>

<p>
  <strong>Close at:</strong>
  <%= @hotel.close_at %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @hotel.phone %>
</p>

<p>
  <strong>Fax:</strong>
  <%= @hotel.fax %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @hotel.zip_code %>
</p>

<p>
  <strong>Is economic:</strong>
  <%= @hotel.is_economic %>
</p>

<p>
  <strong>Is apartmen:</strong>
  <%= @hotel.is_apartmen %>
</p>

<p>
  <strong>Reocar city:</strong>
  <%= @hotel.reocar_city_id %>
</p>

<p>
  <strong>City name:</strong>
  <%= @hotel.city_name %>
</p>

<p>
  <strong>City:</strong>
  <%= @hotel.city_id %>
</p>

<p>
  <strong>Business zone:</strong>
  <%= @hotel.business_zone %>
</p>

<p>
  <strong>Business zone:</strong>
  <%= @hotel.business_zone_id %>
</p>

<p>
  <strong>Attached business zone:</strong>
  <%= @hotel.attached_business_zone %>
</p>

<p>
  <strong>District:</strong>
  <%= @hotel.district %>
</p>

<p>
  <strong>District:</strong>
  <%= @hotel.district_id %>
</p>

<p>
  <strong>Baidu location:</strong>
  <%= @hotel.baidu_location %>
</p>

<p>
  <strong>Google location:</strong>
  <%= @hotel.google_location %>
</p>

<p>
  <strong>Star:</strong>
  <%= @hotel.star %>
</p>

<p>
  <strong>Credit cards:</strong>
  <%= @hotel.credit_cards %>
</p>

<p>
  <strong>Status:</strong>
  <%= @hotel.status %>
</p>

<p>
  <strong>Review count:</strong>
  <%= @hotel.review_count %>
</p>

<p>
  <strong>Review good:</strong>
  <%= @hotel.review_good %>
</p>

<p>
  <strong>Review poor:</strong>
  <%= @hotel.review_poor %>
</p>

<p>
  <strong>Review score:</strong>
  <%= @hotel.review_score %>
</p>

<p>
  <strong>Intro:</strong>
  <%= @hotel.intro %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>Traffic:</strong>
  <%= @hotel.traffic %>
</p>

<p>
  <strong>Has coupon:</strong>
  <%= @hotel.has_coupon %>
</p>

<p>
  <strong>Themes:</strong>
  <%= @hotel.themes %>
</p>

<p>
  <strong>Room total:</strong>
  <%= @hotel.room_total %>
</p>

<p>
  <strong>Facilities:</strong>
  <%= @hotel.facilities %>
</p>

<p>
  <strong>Stay leave info:</strong>
  <%= @hotel.stay_leave_info %>
</p>

<p>
  <strong>Recommend level:</strong>
  <%= @hotel.recommend_level %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElongHotel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>